import { Box } from '@chakra-ui/react'
import Head from 'next/head'
import AboutUs from './Components/AboutUs'
import Customer from './Components/Customer'
import Faq from './Components/Faq'
import Footer from './Components/Footer'
import Intro from './Components/Intro'
import MobNav from './Components/MobNav'
import OurServices from './Components/OurServices'
import { QuoteButton } from './Components/QuoteButton'
import Whyus from './Components/Whyus'
import Home from './Home'
import Banner from './Components/Banner'
import About from './Components/About'

const MainDisplay = () => {
  return (
    <div>
      <Head>
      {/* <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet"/> */}

        <title>elite Cleaning</title>
        
        <meta name="description" content="Generated by create next app" />
   
            </Head>
        
          {/* <Home/> */}
          <Banner/>
          <About/>
         <Box position="fixed" bottom='0' right='0' zIndex='300' >
         <QuoteButton />
         </Box>
         <Box backgroundColor='whitesmoke'>
           <MobNav/>
           <Intro/>
           <Whyus/>
           <Customer/>
           <Faq/>
           <OurServices/>
           <AboutUs/>
           <Footer/>
         </Box>
          
     
    </div>
  )
}

export default MainDisplay
