import { Box } from '@chakra-ui/react'
import Head from 'next/head'
import AboutUs from '../components/AboutUs'
import Faq from '../components/Faq'
import Footer from '../components/Footer'
import Intro from '../components/Intro'
import MobNav from '../components/MobNav'
import OurServices from '../components/OurServices'
import { QuoteButton } from '../components/QuoteButton'
import Whyus from '../components/Whyus'
import Home from './Home'
import Banner from '../components/Banner'
import About from '../components/About'
import Elite from '../components/Elite/Elite'
import Comment from '../components/Elite/Comment'

const MainDisplay = () => {
  return (
    <div>
      <Head>
      {/* <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" />
<link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet"/> */}

        <title>elite Cleaning</title>
        
        <meta name="description" content="Generated by create next app" />
   
            </Head>
        
          {/* <Home/> */}
          <Banner/>
          <About/>
         <Box position="fixed" bottom='0' right='0' zIndex='300' >
         {/* <QuoteButton /> */}
         </Box>
         <Box backgroundColor='whitesmoke'>
           <MobNav/>
           {/* <Intro/> */}
           <Whyus/>
           <Elite/>
           <Comment/>
           {/* <Customer/> */}
           <Faq/>
           {/* <OurServices/> */}
           {/* <AboutUs/> */}
           <Footer/>
         </Box>
          
     
    </div>
  )
}

export default MainDisplay
